package dev.auto.blockengine.api.resourcepack;

import org.bukkit.NamespacedKey;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Code-defined item model emitted into BlockEngine's generated resource pack.
 *
 * <p>A generated item model writes two files:</p>
 *
 * <ul>
 *     <li>{@code assets/<namespace>/models/item/<key>.json}</li>
 *     <li>{@code assets/<namespace>/items/<key>.json}</li>
 * </ul>
 *
 * <p>The resulting {@link #key()} can be used as an item model override on a
 * managed display appearance. The model references textures by resource-pack
 * path; it does not embed image data.</p>
 */
public final class GeneratedItemModel {
    private final @NotNull NamespacedKey key;
    private final @NotNull String parent;
    private final @NotNull Map<String, String> textures;

    private GeneratedItemModel(@NotNull Builder builder) {
        key = Objects.requireNonNull(builder.key, "key");
        parent = Objects.requireNonNull(builder.parent, "parent");
        textures = Collections.unmodifiableMap(new LinkedHashMap<>(builder.textures));
    }

    /**
     * Starts building a generated item model.
     *
     * @param key item model key to generate
     * @return model builder
     */
    public static @NotNull Builder builder(@NotNull NamespacedKey key) {
        return new Builder(key);
    }

    /**
     * Returns the item model key generated by this definition.
     *
     * @return namespaced item model key
     */
    public @NotNull NamespacedKey key() {
        return key;
    }

    /**
     * Returns the model parent written into model JSON.
     *
     * @return model parent, such as {@code minecraft:item/generated}
     */
    public @NotNull String parent() {
        return parent;
    }

    /**
     * Returns the immutable texture slot map.
     *
     * @return texture slots keyed by model texture name
     */
    public @NotNull Map<String, String> textures() {
        return textures;
    }

    /**
     * Returns a texture slot as a {@link TextureRef}.
     *
     * @param layer texture layer name, such as {@code layer0} or {@code all}
     * @return texture reference for that layer
     * @throws IllegalArgumentException if the layer is not defined
     */
    public @NotNull TextureRef texture(@NotNull String layer) {
        String texture = textures.get(layer);
        if (texture == null) {
            throw new IllegalArgumentException("Generated model does not define texture layer: " + layer);
        }
        return TextureRef.of(texture);
    }

    /**
     * Registry passed to plugins during resource-pack generation.
     */
    public interface Registry {
        /**
         * Registers a generated item model for the current pack generation pass.
         *
         * @param model model definition to emit into the generated pack
         */
        void register(@NotNull GeneratedItemModel model);
    }

    /**
     * Mutable builder for {@link GeneratedItemModel}.
     */
    public static final class Builder {
        private final @NotNull NamespacedKey key;
        private @NotNull String parent = "minecraft:item/generated";
        private final @NotNull Map<String, String> textures = new LinkedHashMap<>();

        private Builder(@NotNull NamespacedKey key) {
            this.key = Objects.requireNonNull(key, "key");
        }

        /**
         * Sets the parent model.
         *
         * @param parent parent model id
         * @return this builder
         */
        public @NotNull Builder parent(@NotNull String parent) {
            this.parent = Objects.requireNonNull(parent, "parent");
            return this;
        }

        /**
         * Sets or clears a texture slot.
         *
         * @param layer texture slot name
         * @param texture texture reference string, or null/blank to remove it
         * @return this builder
         */
        public @NotNull Builder texture(@NotNull String layer, @Nullable String texture) {
            if (texture == null || texture.isBlank()) {
                textures.remove(layer);
                return this;
            }
            textures.put(Objects.requireNonNull(layer, "layer"), texture);
            return this;
        }

        /**
         * Sets or clears a texture slot.
         *
         * @param layer texture slot name
         * @param texture texture reference, or null to remove it
         * @return this builder
         */
        public @NotNull Builder texture(@NotNull String layer, @Nullable TextureRef texture) {
            return texture(layer, texture == null ? null : texture.value());
        }

        /**
         * Sets or clears the common {@code layer0} texture slot.
         *
         * @param texture texture reference string, or null/blank to remove it
         * @return this builder
         */
        public @NotNull Builder layer0(@Nullable String texture) {
            return texture("layer0", texture);
        }

        /**
         * Sets or clears the common {@code layer0} texture slot.
         *
         * @param texture texture reference, or null to remove it
         * @return this builder
         */
        public @NotNull Builder layer0(@Nullable TextureRef texture) {
            return texture("layer0", texture);
        }

        /**
         * Builds an immutable generated model definition.
         *
         * @return generated item model definition
         */
        public @NotNull GeneratedItemModel build() {
            return new GeneratedItemModel(this);
        }
    }
}
